---
- hosts: all
  tasks:
  - name: Install req'd packages
    dnf:
    notify: enable_and_start_pcscd
      state: present
      name:
      - gnutls-utils
      - opensc
      - pcsc-lite
      - pcsc-lite-ccid
      - pcsc-lite-libs

  - name: Execute add-dod-certs.sh
    script: add-dod-certs.sh

  handlers:
  - name: enable_and_start_pcscd
    systemd:
      enabled: yes
      state: started
      name: pcscd